security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        nao_app:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            provider: nao_app
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mon-compte, roles: ROLE_USER }
        - { path: ^/espace-administration, roles: ROLE_NATURALIST }

    role_hierarchy:
        ROLE_NATURALIST: ROLE_USER
        ROLE_ADMIN: ROLE_NATURALIST